version: "3"
services:
  memcached:
    image: memcached:1.5-alpine

  redis:
    image: redis:5.0-alpine

  convertit:
     image: makinacorpus/convertit:latest

  screamshotter:
     image: makinacorpus/screamshotter:latest

  celery:
    image: geotrekce/admin:${GEOTREK_VERSION:-latest}
    env_file:
      - .env
    volumes:
      - ./var:/app/src/var
    depends_on:
      - memcached
      - redis
    user: ${USER_ID:-0}:${GROUP_ID:-0}
    command: celery -A geotrek worker -c 1

  web:
    image: geotrekce/admin:${GEOTREK_VERSION:-latest}
    env_file:
      - .env
    ports:
      - "${WEB_PORT:-8001}:8000"
    volumes:
      - ./var:/app/src/var
    depends_on:
      - memcached
      - redis
      - screamshotter
      - convertit
    user: ${USER_ID:-0}:${GROUP_ID:-0}

  api:
    image: geotrekce/admin:${GEOTREK_VERSION:-latest}
    env_file:
      - .env
    ports:
      - "${API_PORT:-8002}:8000"
    volumes:
      - ./var:/app/src/var
    depends_on:
      - memcached
      - redis
    user: ${USER_ID:-0}:${GROUP_ID:-0}
